#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cpan
# autospec version: v21
# autospec commit: 94c6be0
#
Name     : perl-DBD-SQLite
Version  : 1.76
Release  : 39
URL      : https://cpan.metacpan.org/authors/id/I/IS/ISHIGAKI/DBD-SQLite-1.76.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/I/IS/ISHIGAKI/DBD-SQLite-1.76.tar.gz
Summary  : 'Self Contained SQLite RDBMS in a DBI Driver'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-2.0
Requires: perl-DBD-SQLite-license = %{version}-%{release}
Requires: perl-DBD-SQLite-perl = %{version}-%{release}
Requires: sqlite-autoconf-lib
BuildRequires : buildreq-cpan
BuildRequires : perl(Bundle::DBI)
BuildRequires : perl(Digest::MD5)
BuildRequires : sqlite-autoconf-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Enable-build-link-with-system-sqlite3-lib.patch
Patch2: backport-Tweak-for-3.37.0.patch

%description
NAME
DBD::SQLite - Self-contained RDBMS in a DBI Driver
SYNOPSIS
use DBI;
my $dbh = DBI->connect("dbi:SQLite:dbname=$dbfile","","");

%package dev
Summary: dev components for the perl-DBD-SQLite package.
Group: Development
Provides: perl-DBD-SQLite-devel = %{version}-%{release}
Requires: perl-DBD-SQLite = %{version}-%{release}

%description dev
dev components for the perl-DBD-SQLite package.


%package license
Summary: license components for the perl-DBD-SQLite package.
Group: Default

%description license
license components for the perl-DBD-SQLite package.


%package perl
Summary: perl components for the perl-DBD-SQLite package.
Group: Default
Requires: perl-DBD-SQLite = %{version}-%{release}

%description perl
perl components for the perl-DBD-SQLite package.


%prep
%setup -q -n DBD-SQLite-1.76
cd %{_builddir}/DBD-SQLite-1.76
%patch -P 1 -p1
%patch -P 2 -p1
pushd ..
cp -a DBD-SQLite-1.76 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} -I. Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test || :

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-DBD-SQLite
cp %{_builddir}/DBD-SQLite-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/perl-DBD-SQLite/ac65ff6b8120c21db8e28bbfbf89a2da90009f97 || :
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/DBD::SQLite.3
/usr/share/man/man3/DBD::SQLite::Constants.3
/usr/share/man/man3/DBD::SQLite::Cookbook.3
/usr/share/man/man3/DBD::SQLite::Fulltext_search.3
/usr/share/man/man3/DBD::SQLite::VirtualTable.3
/usr/share/man/man3/DBD::SQLite::VirtualTable::FileContent.3
/usr/share/man/man3/DBD::SQLite::VirtualTable::PerlData.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-DBD-SQLite/ac65ff6b8120c21db8e28bbfbf89a2da90009f97

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
